import { Slide, ToastContainer } from "react-toastify";
import {  ThemeProvider } from "./components/ThemeProvider";
import "./globals.css";



export const metadata = {
  title: "Admin",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        
      >
      <ThemeProvider
        attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange

        >
          
<ToastContainer
position="top-center"
autoClose={2500}
limit={2}
hideProgressBar
newestOnTop={false}
closeOnClick
rtl={false}
pauseOnFocusLoss
draggable
pauseOnHover
theme="light"
transition={Slide}
/>

        {children}
    </ThemeProvider>
      </body>
    </html>
  );
}
